entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
  websecure:
    address: ":443"
    http:
      tls: true

ping: true

http:
  middlewares:
    testHeader:
      headers:
        accessControlAllowMethods: [ "GET", "OPTIONS", "PUT", "POST" ]
        accessControlAllowOriginList: "*"
        accessControlAllowCredentials: true

api:
  dashboard: true

providers:
  docker:
    exposedByDefault: false
    network: "web"

  file:
    filename: /etc/traefik/config.yml
    watch: true

log:
  level: "DEBUG"
  filePath: "/opt/traefik/traefik.log"
  format: "json"

accessLog:
  filePath: "/opt/traefik/access.log"
  format: "json"